### ISSUE TITLE
BEETL versions don't match up with release?

### ISSUE THREAD

**Issue by tseemann** [BEETL/BEETL#10]
Release is 0.10.0 but README say 1.1 ?

@janinl  Can you make a new 1.1 release om the 'Releases' tab so we can package?

https://github.com/BEETL/BEETL/commit/6c240ea802f9a4cba6e62bed6a69fa67b68a6e8c

**Comment by janinl** [comment]
Done, sorry for the "slight" delay...

**Comment by tseemann** [comment]
😂  last week i got a response after 4.5 years on an issue!
