### ISSUE TITLE
define statment in tools.hh causes make to fail

### ISSUE THREAD

**Issue by jo-mc** [BEETL/BEETL#13]
File: src/shared/Tools.hh
Line: 39
-----------------------------------------------------------------------------------------------------------------------------
#define BUILD_LCP 1	   0	//If it is set to 1, it uses larger structures to allow --generate-lcp
-----------------------------------------------------------------------------------------------------------------------------
you have two values -> error in make. 

I guess you meant to set it to 0, and have 1 in the comment?

**Comment by janinl** [comment]
Thanks jo-mc

Hi @giovannarosone , what did you intend to change? This is your commit from 3 months ago... https://github.com/BEETL/BEETL/commit/0ce9538a7509544ee117968a51d4f890fc87ce18

Should we set this to 0?

**Comment by giovannarosone** [comment]
Thanks  jo-mc.
I fixed the tools file.
I unintentionally introduced the double value for the macro when I made the last change.
