### ISSUE TITLE
How install this software in my pc ?

### ISSUE THREAD

**Issue by Philips-omica-io** [BEETL/BEETL#15]
im new in this, always i try to follow the manual of instalation, but in this case i didnt find, may you explain to me how do it please?

**Comment by giovannarosone** [comment]
Hi,
Thank you for your question.
You can find more details on
https://github.com/BEETL/BEETL/blob/RELEASE_1_1_0/doc/BEETL.md

(see also https://github.com/BEETL/BEETL/tree/RELEASE_1_1_0/doc)
