### ISSUE TITLE
missing compilation script

### ISSUE THREAD

**Issue by jts** [BEETL/BEETL#5]
doc/BEETL.md refers to a script `bootstrap_with_autotools` which presumably runs aclocal, autoconf, etc. This script is missing from the current github repository.

**Comment by janinl** [comment]
Hi Jared,
Thanks for this. I'll add the script (or update the documentation).
You correctly guessed what it was doing ;) (The script is actually not needed, as we run it before sending releases to this BEETL repository).
Cheers,
Lilian
