### ISSUE TITLE
Setting maximum memory before writing to temporary files.

### ISSUE THREAD

**Issue by anandpatel-sci** [BEETL/BEETL#8]
I am running into memory overuse issues when running BEETL on a server.

Is there a parameter for setting maximum memory used by `beetl extend` before writing to temporary files?

thx, Anand

**Comment by janinl** [comment]
Hi Anand,

No, sorry, there's no way to limit the memory used.

Lilian

**Comment by anandpatel-sci** [comment]
Well, that's discouraging.
Is there anyway to set a limit at compile time? Our server has 128GB of RAM, and one `bwt extend` run is using >75% of memory, and being auto-killed by an Admin process. 

Thanks for the quick response.
