### ISSUE TITLE
LCP values are either 0 or 1

### ISSUE THREAD

**Issue by mikael-s** [BEETL/BEETL#9]
I'm trying to use BEETL to generate a BWT and a LCP array, but I'm quite disappointed by the obtained LCP array. In the -Lxx files I only have 4-byte integers whose values are either 0 or 1.

Here is a short example:

```
>seq1
atagcaatagcaatagcaagcaattttatagca
>seq2
atagcaatagcaatggcaagcaattttatagca
```

I ran BEETL using the command `beetl-bwt --generate-lcp --output-format ASCII -i seq.fa`. I'm using BEETL 1.1.0 (compiled with g++-4.9).

The first 4-byte integer in each -Lxx files is a 0 and the other values are a 1. This would correspond to the LCP restricted to the first letter, which brings little information!

Am I doing anything wrong? Thanks!

**Comment by giovannarosone** [comment]
Fixed
